
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/_components/_Navbar/NavBar";
import "../../node_modules/@fortawesome/fontawesome-free/css/all.min.css"
import NavContextProvider from "../../Context/NavContext";
import toast, { Toaster } from 'react-hot-toast';
import { CartItemsContextProvider } from "../../Context/CartItemsContext";
import { IconsContextProvider } from "../../Context/IconsContext";
import Footer from "./footer/page";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavContextProvider>
          <CartItemsContextProvider>
            <IconsContextProvider>

          
          

         
          


            <Toaster />

            <NavBar/>
            {children}
            <Footer/>
           </IconsContextProvider>
          </CartItemsContextProvider>
        </NavContextProvider>
      </body>
    </html>
  );
}
